name: api user docker hub image

# 触发条件：在 push 到 main 分支后
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build
        run: chmod +x ./gradlew && ./gradlew :moneynote-api-user:build
      - run: ls ./moneynote-api-user/build/libs/
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./moneynote-api-user/Dockerfile
          push: true
          tags: markliu2018/moneywhere-api-user:latest