name: docker hub

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
      - name: Build
        run: ./gradlew :moneynote-api-user:build
      - name: Build the Docker image
        run: docker build ./moneynote-api-user --file Dockerfile
      - name: echo
        run: echo $GITHUB_REF_NAME
